import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SWRProvider } from "@/providers/SWRProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Script from "next/script";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script 
          src="https://mathjax.codeforces.org/MathJax.js?config=TeX-AMS_HTML-full" 
          strategy="beforeInteractive" 
        />
      </head>
      <body className="min-h-full flex flex-col">
        <SWRProvider>
          {children}
        </SWRProvider>
      </body>
    </html>
  );
}
